### ISSUE TITLE
5分間チャットに関して

### ISSUE THREAD

**Issue by pandeiro245** [fukajun/245cloud-app#1]
* [x] command+Vでクリップボード貼り付けたい
* [x] 本文中のURLをクリックしたらその：URLが開くようにしたい

**Comment by fukajun** [comment]
@pandeiro245 おーーありがとうございます！！！

**Comment by fukajun** [comment]
とりあえず、コピペについてできたので次のバージョンでリリースします。

**Comment by fukajun** [comment]
むむむ
http://d.hatena.ne.jp/hasegawayosuke/20160124/p1

**Comment by fukajun** [comment]
electron 内部で開くのはよくないとのことなので
https://github.com/atom/electron/issues/1344
を利用しようかと思います。

**Comment by fukajun** [comment]
コピペ機能については、#3 で実装しました。

**Comment by fukajun** [comment]
外部リンクへのURLは、普通にブラウザで開くようにしました。 #4

**Comment by fukajun** [comment]
@pandeiro245 リリースしたので、アップデートしてみてください。
https://github.com/fukajun/245cloud-app/releases/tag/v0.1.0

**Comment by pandeiro245** [comment]
どっちもいけてました！！
