### ISSUE TITLE
Macを一度フリーズさせてサイド開くと画面が真っ白になることがある？

### ISSUE THREAD

**Issue by pandeiro245** [fukajun/245cloud-app#14]
![image](https://cloud.githubusercontent.com/assets/125965/14809484/5a188ef2-0bc8-11e6-8621-e8eb0dff935e.png)

ちょくちょくこうなるのでcommand+qで閉じて開き直してますー。

**Comment by fukajun** [comment]
ありがとうございます。

**Comment by fukajun** [comment]
リロードボタンで一旦クローズ
