### ISSUE TITLE
5分チャットの文字が一部切れてしまっている

### ISSUE THREAD

**Issue by pandeiro245** [fukajun/245cloud-app#6]
![image](https://cloud.githubusercontent.com/assets/125965/13804625/e6550e38-eb91-11e5-9bdb-8afea54dddf1.png)

「２」という文字列がまるまる隠れちゃってるっぽい

```
macアプリで左右切れるテスト１２３４５６７８９０１２３４５６７８９０１２３４５６７８９０
```

これは本体も修正必要かも？

**Comment by fukajun** [comment]
デフォルトのウィンドウサイズをもう少し広げれば良いですね。
実はウィンドウの端にカーソルを持っていくと、幅広げることできます。

**Comment by fukajun** [comment]
https://github.com/fukajun/245cloud-app/releases/tag/v0.2.0

で対応しました。
