### ISSUE TITLE
ショートカットキーでWindowを表示したい

### ISSUE THREAD

**Issue by fukajun** [fukajun/245cloud-app#9]
https://github.com/atom/electron/blob/master/docs/api/global-shortcut.md

**Comment by fukajun** [comment]
@pandeiro245 どうして？ショートカット欲しいんでしたっけ？

**Comment by pandeiro245** [comment]
@fukajun 245cloudやろうと思った時、
現在：マウスを右上に持ってきてワンクリックして開く
理想：ショートカットキーで開く
というイメージで後者の方が0.2秒ほど手軽になるかなっていうｗ

**Comment by fukajun** [comment]
なるほど、確かにアクセスのしやすさ大切ですね。実装したくなりました。

**Comment by pandeiro245** [comment]
目をつぶっても245cloudをスタートできる感、いいですよね。はらぱん氏もマウス使わないでって言ってた気がする

**Comment by fukajun** [comment]
`ctrl + shift + p` (pomo) で前回再生したものが再度流れるようになります。
前回がない場合は、無音がスタートっていうのはどうでしょう？

**Comment by pandeiro245** [comment]
> 無音がスタートっていうのはどうでしょう？

レアケースだと思いますし、無音でいいかと！

**Comment by fukajun** [comment]
単純にwindowを開くだけのショートカットもあった方がいいなとも思いました。
`ctrl + shift + m` とかにしようかな

**Comment by fukajun** [comment]
https://github.com/fukajun/245cloud-app/releases/tag/v0.2.0

で対応しました。
